spring.application.name=SpringGame

spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/springboot_game
spring.datasource.username=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.encoding=utf-8
spring.sql.init.mode=always

# テスト用にEntityからテーブルを自動生成するため
spring.jpa.hibernate.ddl-auto=create
# data.sqlでのデータ投入を、テーブル生成後（JPA起動後）に行うため
spring.jpa.defer-datasource-initialization=true